### ISSUE TITLE
Error when -d or -p is present

### ISSUE THREAD

**Issue by Ingvix** [pbnoxious/yt2mpd#3]
I'm unable to prune or delete the track after the play. This error comes around:
```
Traceback (most recent call last):
  File "/home/ingvix/.local/bin//yt2mpd", line 6, in <module>
    yt2mpd.main()
  File "/home/ingvix/.local/lib/python3.8/site-packages/yt2mpd/yt2mpd.py", line 88, in main
    prune_dir(oldfiles, settings.music_dir)
  File "/home/ingvix/.local/lib/python3.8/site-packages/yt2mpd/yt2mpd.py", line 74, in prune_dir
    curr_playlist = mpd_query.communicate()[0].decode('UTF-8').split("\n")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 183371: invalid start byte
```

**Comment by pbnoxious** [comment]
Hi, sorry for the late reply (haven't really looked at he repo in a long time): I can't reproduce this locally, both work just fine for me.
If you are still interested in the issue, I'd likely need further info.

The error occurs when it tries to decode the filenames of the current mpd playlist into utf-8, and it complains that there is some non-unicode byte in there.
What OS are you using? Can you give me an exemplary output of `mpc filenames -f %file%` ?
